# /opt/docker-compose.yml
---
version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs

  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes:
      - ./appdata/plex:/config
      - ${STORAGE_PATH}/shares:/data
    tmpfs:
      - /tmp
      - /transcode
    hostname: ${PLEX_HOSTNAME}
    environment:
      - PUID=${DOCKER_USER_ID}
      - PGID=${DOCKER_USER_GROUP_ID}
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - VIRTUAL_HOST=${PLEX_HOSTNAME},${PLEX_VIRTUAL_HOST}
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=${PLEX_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  nextcloud-web:
    image: nginx
    container_name: nextcloud_webserver
    links:
      - nextcloud-app
      - collabora
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes_from:
      - nextcloud-app
    volumes:
      - ./appdata/nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=${NEXTCLOUD_VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${NEXTCLOUD_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  nextcloud-app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - nextcloud-db
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes:
      - ./appdata/nextcloud/apps:/var/www/html/apps
      - ./appdata/nextcloud/config:/var/www/html/config
      - ${STORAGE_PATH}/cloud:/var/www/html/data

  nextcloud-db:
    image: mariadb
    container_name: nextcloud_db
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes:
      - ./appdata/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}

  redis:
    image: redis
    container_name: redis
    networks:
      - proxy-tier
    restart: unless-stopped

  collabora:
    image: collabora/code
    container_name: collabora
    cap_add:
      - MKNOD
    networks:
      - proxy-tier
    restart: unless-stopped
    environment:
      - domain=${NEXTCLOUD_VIRTUAL_HOST}

  home-assistant:
# We build the image ourself and install dependencies necessary for tradfri until these issues are resolved:
# - https://github.com/home-assistant/home-assistant/issues/10376
# - https://github.com/home-assistant/home-assistant/issues/10048
#    image: homeassistant/home-assistant
    build:
      context: .
      dockerfile: Dockerfile.home-assistant
    container_name: home-assistant
    links:
      - plex
    ports:
      - 8123:8123
    networks:
      - proxy-tier
    restart: unless-stopped
    volumes:
      - ./appdata/home-assistant:/config
    environment:
      - TZ=${TIMEZONE}
      - VIRTUAL_HOST=${HOME_ASSISTANT_VIRTUAL_HOST}
      - VIRTUAL_PORT=8123
      - LETSENCRYPT_HOST=${HOME_ASSISTANT_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    ports:
      - 8200:8200
    restart: unless-stopped
    volumes:
      - ./:/source/opt
      - ${STORAGE_PATH}:/source/storage

networks:
  proxy-tier:
    external:
      name: nginx-proxy
